site_name: Project Road to Go
site_url: https://localhost
theme:
  name: material
  palette: 
    scheme: slate
    primary: blue
    accent: blue
  font:
    text: Kadwa
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - toc.follow
    - navigation.top
    - navigation.footer

nav:
  - Home:
    - index.md
    - Objetivos do Projeto: objetivos.md
    - Metodologia de Estudos: metodologia.md
  - Blog:
    - blog/index.md

plugins:
  # - meta:
  #     enabled: true
  - search
  - blog:
      enabled: true
      # blog_dir: blog
      blog_toc: true
      # post_dir: "{blog}/posts"
      # post_url_max_categories: 1
      # post_slugify_separator: "-"
      # post_excerpt_max_authors: 1
      # post_excerpt_max_categories: 5
      # post_excerpt_separator: <!-- more -->
      # post_readtime: true
      # post_readtime_words_per_minute: 265
      archive: false
      # archive_name: Archive
      # archive_pagination: true
      # archive_pagination_per_page: 10
      # archive_toc: false
      # categories: true
      # categories_name: Categories
      # categories_slugify_separator: "-"
      # categories_pagination: true
      # categories_pagination_per_page: 10
      # categories_toc: false
      # authors: true
      # authors_file: "{blog/.authors.yml"}
      # authors_profiles: false
      # authors_profiles_name: Authors
      # authors_profiles_pagination: true
      # authors_profiles_pagination_per_page: 10
      # authors_profiles_toc: false
      # pagination: true
      # pagination_per_page: 10
      # pagination_keep_content: false
      # draft: false
      # draft_on_serve: true
      # draft_if_future_date: false
  - social:
      enabled: false
      # cache: true
      # cache_dir: .cache/plugins/social
      # cards: true
      # log: true
      # cards_dir: assets/images/social
      # cards_layout_dir: layouts
      # debug: true
      # debug_on_build: false
      # debug_grid: true
      # debug_grid_step: 32
      # debug_color: yellow
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences